#
# Makefile
#
# $Id: //poco/1.7/Net/samples/ifconfig/Makefile#1 $
#
# Makefile for Poco download
#

include $(POCO_BASE)/build/rules/global

objects = ifconfig

target         = ifconfig
target_version = 1
target_libs    = PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/exec
