#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          WebTunnelAgent
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop macchina.io REMOTE WebTunnelAgent
### END INIT INFO

. /lib/lsb/init-functions

SERVICE=WebTunnelAgent
PIDFILE=/var/run/${SERVICE}.pid
EXEC=/usr/local/sbin/$SERVICE
CONFIG=/etc/${SERVICE}.properties

if [ ! -x $EXEC ] ; then
	echo "No $EXEC executable found"
	exit 0
fi

start() {
	log_daemon_msg "Starting $SERVICE: "
	$EXEC --pidfile=$PIDFILE --daemon --config=$CONFIG
	log_end_msg 0
}

stop() {
	log_daemon_msg "Stopping $SERVICE: "
	if [ -f $PIDFILE ] ; then
		pid=`cat $PIDFILE`
		kill $pid
		log_end_msg 0
	else
		log_end_msg 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload|condrestart)
		stop
		sleep 5
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

exit 0

