#
# Makefile
#
# $Id: //poco/1.7/Foundation/samples/URI/Makefile#3 $
#
# Makefile for Poco URI
#

include $(POCO_BASE)/build/rules/global

objects = URI

target         = URI
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
